main = "./src/index.ts"
compatibility_date = "2022-05-03"
name = "breathic-api-worker-dev"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "breathic-api-database-dev"
database_id = "fdc8af23-a208-401e-be0a-fbdd85148abe"

[[r2_buckets]]
binding = 'R2_READINGS' # i.e. available in your Worker on env.DB
bucket_name = 'breathic-api-readings-bucket-dev'