main = "./src/index.ts"
compatibility_date = "2022-05-03"
name = "breathic-api-worker-production"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "breathic-api-database-production"
database_id = "250f4235-0128-47ec-99fa-df7f2dc40b5e"

[[r2_buckets]]
binding = 'R2_READINGS' # i.e. available in your Worker on env.DB
bucket_name = 'breathic-api-readings-bucket-production'