main = "./src/index.ts"
compatibility_date = "2022-05-03"
name = "breathic-api-worker-staging"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "breathic-api-database-staging"
database_id = "dea4d0f5-7818-4e4a-a290-8c05c6a38a59"

[[r2_buckets]]
binding = 'R2_READINGS' # i.e. available in your Worker on env.DB
bucket_name = 'breathic-api-readings-bucket-staging'