main = "./src/index.ts"
compatibility_date = "2022-05-03"
name = "breathic-api-worker"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "breathic-api-database"
database_id = "cc48d92f-78f2-4e5b-8c38-b512a8a9266e"

[[r2_buckets]]
binding = 'R2_READINGS' # i.e. available in your Worker on env.DB
bucket_name = 'breathic-api-readings-bucket'